### ISSUE TITLE
Long function

### ISSUE THREAD

**Issue by otajor** [smooth-operators-fac/portfolio#36]
Your createModal function could use some refactoring. https://github.com/smooth-operators-fac/portfolio/blob/master/js/profile.js#L12-L30

Firstly, it is quite long (18 lines). I know some of that is comments, but it's still too long and you could probably break it down into smaller functions to make the whole thing easier to read.
Something like:

``` javascript
function createModal (imageSrc, biography) {
  var bio = createBio(biography);
  var img = createImage(imageSrc);
  appendToModal(bio, img);
  showModal();
}
```

cf. http://deviq.com/separation-of-concerns/

**Comment by bradreeder** [comment]
Many thanks for taking the time to raise this.

I agree the function became messy. We ended up adding the comments as we needed a way to differentiate the many parts of what the function does. I've implemented your suggestion and read the link, and will keep in mind in the future.

**Comment by otajor** [comment]
👍  Nice, looks good. 

FYI generally good practice to let people close the issues that they made so I would close this after seeing that you've fixed it.

Also good to link to the PR that solves the issue in your comment like: #42

**Comment by bradreeder** [comment]
Okay, sorry, thanks for letting me know. 👍
